{
  "openapi": "3.0.3",
  "x-stoplight": {
    "id": "snkgxctdxuqc9"
  },
  "info": {
    "title": "API horaires",
    "version": "2.0.0",
    "description": "Service REST pour les heures d'ouvertures des services de la Direction des bibliothèques, Université de Montréal",
    "contact": {
      "name": "Christian Rémillard",
      "url": "https://github.com/bibudem/api-horaires",
      "email": "christian.remillard@umontreal.ca"
    },
    "license": {
      "name": "MIT",
      "url": "https://raw.githubusercontent.com/bibudem/api-horaires/main/LICENSE"
    }
  },
  "tags": [
    {
      "name": "À propos"
    },
    {
      "name": "Horaires"
    },
    {
      "name": "Horaires par bibliothèque"
    },
    {
      "name": "Liste de code de bibliothèque"
    },
    {
      "name": "Liste des services"
    },
    {
      "name": "Liste des types de périodes"
    }
  ],
  "paths": {
    "/liste": {
      "get": {
        "summary": "Retourne la liste des bibliothèques ayant un horaire",
        "operationId": "listBibs",
        "responses": {
          "200": {
            "$ref": "#/components/responses/BibsResponse"
          },
          "500": {
            "$ref": "#/components/responses/InternalErrorResponse"
          }
        },
        "description": "Retourne un objet contenant la liste des codes de biblithèques",
        "tags": [
          "Liste de code de bibliothèque"
        ]
      },
      "parameters": []
    },
    "/services": {
      "get": {
        "summary": "Liste des services ayant un horaire",
        "tags": [
          "Liste des services"
        ],
        "responses": {
          "200": {
            "$ref": "#/components/responses/ServicesResponse"
          }
        },
        "operationId": "listServices",
        "description": "Retourne un objet contenant la liste des types de services"
      }
    },
    "/periodes": {
      "get": {
        "summary": "Liste des types de périodes",
        "tags": [
          "Liste des types de périodes"
        ],
        "responses": {
          "200": {
            "$ref": "#/components/responses/PeriodesResponse"
          }
        },
        "operationId": "listPeriodes",
        "description": "Retourne un objet contenant la liste des types de périodes"
      }
    },
    "/about": {
      "$ref": "https://raw.githubusercontent.com/bibudem/api-communs/main/src/about.json#/paths/~1about"
    },
    "/": {
      "get": {
        "parameters": [
          {
            "$ref": "#/components/parameters/debut"
          },
          {
            "$ref": "#/components/parameters/fin"
          },
          {
            "$ref": "#/components/parameters/ouvert"
          },
          {
            "$ref": "#/components/parameters/bibs"
          },
          {
            "$ref": "#/components/parameters/format"
          }
        ],
        "responses": {
          "200": {
            "$ref": "#/components/responses/HorairesResponse"
          },
          "400": {
            "$ref": "#/components/responses/RequestValidationError"
          },
          "415": {
            "$ref": "#/components/responses/RequestValidationError"
          },
          "500": {
            "$ref": "#/components/responses/InternalErrorResponse"
          }
        },
        "operationId": "getHoraires",
        "summary": "Liste des horaires",
        "description": "Trouve des horaires en filtrant par bibliothèque et période.\nRetourne les résultats en format `JSON`ou `iCalendar` (ics)\n",
        "x-internal": false,
        "tags": [
          "Horaires"
        ]
      }
    },
    "/{bib}.{format}": {
      "summary": "Liste les nouvelles acquisitions pour une discipline",
      "parameters": [
        {
          "schema": {
            "type": "string",
            "pattern": "ics"
          },
          "name": "format",
          "in": "path",
          "description": "L'extension de fichier \"ics\"",
          "required": true
        },
        {
          "$ref": "#/components/parameters/bib"
        }
      ],
      "get": {
        "parameters": [],
        "responses": {
          "200": {
            "$ref": "#/components/responses/HorairesICSResponse"
          },
          "400": {
            "$ref": "#/components/responses/RequestValidationError"
          },
          "500": {
            "$ref": "#/components/responses/InternalErrorResponse"
          }
        },
        "summary": "Liste des horaires d'une bibliothèque (iCalendar)",
        "description": "Retourne les horaires d'une bibliothèque donnée au format [iCalendar](https://www.rfc-editor.org/rfc/rfc5545.html).",
        "operationId": "getHoraireByBibICS",
        "tags": [
          "Horaires par bibliothèque"
        ]
      }
    },
    "/{bib}": {
      "summary": "Liste les nouvelles acquisitions pour une discipline",
      "get": {
        "parameters": [],
        "responses": {
          "200": {
            "$ref": "#/components/responses/HorairesResponse"
          },
          "400": {
            "$ref": "#/components/responses/RequestValidationError"
          },
          "500": {
            "$ref": "#/components/responses/InternalErrorResponse"
          }
        },
        "summary": "Liste des horaires d'une bibliothèque",
        "description": "Retourne des horaires pour une bibliothèque donnée.",
        "operationId": "getHoraireByBib",
        "tags": [
          "Horaires par bibliothèque"
        ]
      },
      "parameters": [
        {
          "$ref": "#/components/parameters/bib"
        }
      ]
    }
  },
  "components": {
    "schemas": {
      "DateOrDurationDebut": {
        "title": "DateOrDurationDebut",
        "x-stoplight": {
          "id": "f2b9972905848"
        },
        "oneOf": [
          {
            "title": "Duration",
            "type": "string",
            "format": "duration",
            "externalDocs": {
              "url": "https://www.w3.org/TR/xmlschema-2/#duration",
              "description": "3.2.6 duration - XML Schema Part 2: Datatypes Second Edition - W3C Recommendation 28 October 2004"
            }
          },
          {
            "title": "Date",
            "type": "string",
            "format": "date",
            "externalDocs": {
              "url": "https://www.w3.org/TR/xmlschema-2/#date",
              "description": "3.2.9 date - XML Schema Part 2: Datatypes Second Edition - W3C Recommendation 28 October 2004"
            }
          }
        ],
        "type": "string",
        "x-examples": {
          "Une date": "2014-06-06",
          "Une durée d'un mois": "P1M",
          "Les dernière 48 heures": "-PT48H",
          "Le dernier mois": "-P1M"
        }
      },
      "DateOrDurationFin": {
        "title": "DateOrDurationFin",
        "x-examples": {
          "Une date": "2014-06-06",
          "Une date/heure": "2020-06-06T13:00:00-05:00",
          "Une durée d'une journée": "P1D",
          "Les dernière 48 heures": "PT48H",
          "Le dernier mois": "P1M"
        },
        "x-stoplight": {
          "id": "d2932e3502bb4"
        },
        "type": "string",
        "oneOf": [
          {
            "title": "Duration",
            "type": "string",
            "format": "duration",
            "externalDocs": {
              "url": "https://www.w3.org/TR/xmlschema-2/#duration",
              "description": "3.2.6 duration - XML Schema Part 2: Datatypes Second Edition - W3C Recommendation 28 October 2004"
            }
          },
          {
            "title": "Date",
            "type": "string",
            "format": "date",
            "externalDocs": {
              "url": "https://www.w3.org/TR/xmlschema-2/#date",
              "description": "3.2.9 date - XML Schema Part 2: Datatypes Second Edition - W3C Recommendation 28 October 2004"
            }
          }
        ]
      },
      "Horaire": {
        "type": "object",
        "title": "Horaire",
        "description": "Un objet contenant un horaire d'une bibliothèque ou d'un service",
        "x-stoplight": {
          "id": "f5e2f849edcae"
        },
        "properties": {
          "id": {
            "type": "string"
          },
          "date": {
            "type": "string"
          },
          "bibliotheque": {
            "type": "string"
          },
          "debut1": {
            "type": "string"
          },
          "fin1": {
            "type": "string"
          },
          "debut2": {
            "type": "string"
          },
          "fin2": {
            "type": "string"
          },
          "service": {
            "type": "string"
          },
          "periode": {
            "type": "string"
          },
          "sommaire": {
            "type": "string"
          }
        },
        "required": [
          "id"
        ]
      },
      "Horaires": {
        "type": "object",
        "title": "Liste d'horaires",
        "description": "Une liste d'horaires",
        "x-stoplight": {
          "id": "c870347dac8ef"
        },
        "x-examples": {
          "Example 1": {
            "total": 3,
            "evenements": [
              {
                "id": "2843376@bib.umontreal.ca",
                "date": "2023-02-08T05:00:00.000Z",
                "bibliotheque": "ss",
                "debut1": "00:00",
                "fin1": "",
                "debut2": "",
                "fin2": "24:00",
                "service": "regulier",
                "periode": "regulier",
                "sommaire": "ouvert 24h"
              },
              {
                "id": "2852473@bib.umontreal.ca",
                "date": "2023-02-08T05:00:00.000Z",
                "bibliotheque": "ss",
                "debut1": "07:00",
                "fin1": "",
                "debut2": "",
                "fin2": "23:00",
                "service": "reference",
                "periode": "regulier",
                "sommaire": "7h à 23h"
              },
              {
                "id": "2852772@bib.umontreal.ca",
                "date": "2023-02-08T05:00:00.000Z",
                "bibliotheque": "ss",
                "debut1": "09:00",
                "fin1": "13:00",
                "debut2": "14:30",
                "fin2": "17:00",
                "service": "soutien-informatique",
                "periode": "regulier",
                "sommaire": "9h à 13h et 14h30 à 17h"
              }
            ],
            "labels": {
              "bibs": {
                "ss": "Bibliothèque des lettres et sciences humaines"
              },
              "services": {
                "regulier": "Heures d'ouverture",
                "reference": "Référence",
                "soutien-informatique": "Soutien informatique"
              },
              "periodes": {
                "regulier": "Régulier"
              }
            }
          }
        },
        "additionalProperties": false,
        "properties": {
          "total": {
            "type": "integer",
            "description": "Le nombre d'horaires disponibles dans la réponse",
            "minimum": 0
          },
          "evenements": {
            "type": "array",
            "items": {
              "$ref": "#/components/schemas/Horaire"
            }
          },
          "labels": {
            "type": "object",
            "description": "Objet contenant les libellés des bibliothèques, services et périodes disponibles dans cette liste d'horaires",
            "properties": {
              "bibs": {
                "$ref": "#/components/schemas/LabelsMap"
              },
              "services": {
                "$ref": "#/components/schemas/LabelsMap"
              },
              "periodes": {
                "$ref": "#/components/schemas/LabelsMap"
              }
            },
            "required": [
              "bibs",
              "services",
              "periodes"
            ]
          }
        },
        "required": [
          "total"
        ]
      },
      "HttpStatusCode": {
        "title": "Code HTTP",
        "x-stoplight": {
          "id": "58d6f80a0c6d4"
        },
        "type": "integer",
        "example": 200,
        "description": ""
      },
      "HorairesICS": {
        "title": "Fichier iCalendar",
        "x-stoplight": {
          "id": "34e78d7e55ab0"
        },
        "type": "string",
        "description": "Fichier iCalendar",
        "x-examples": {
          "Fichier iCalendar": "BEGIN:VCALENDAR\nVERSION:2.0\nPRODID:-//Direction des bibliothèques - Université de Montréal//API hora\n ires v1.0.0//EN\nCALSCALE:GREGORIAN\nX-WR-TIMEZONE:America/Montreal\nX-PUBLISHED-TTL:P1H\nBEGIN:VTIMEZONE\nTZID:America/Montreal\nBEGIN:DAYLIGHT\nTZNAME:EDT\nDTSTART:19700308T020000Z\nRRULE:FREQ=YEARLY;BYMONTH=3;BYDAY=2SU\nTZOFFSETFROM:-0500\nTZOFFSETTO:-0400\nEND:DAYLIGHT\nBEGIN:STANDARD\nTZNAME:EST\nDTSTART:19701101T020000Z\nRRULE:FREQ=YEARLY;BYMONTH=11;BYDAY=1SU\nTZOFFSETFROM:-0400\nTZOFFSETTO:-0500\nEND:STANDARD\nEND:VTIMEZONE\nBEGIN:VEVENT\nDTSTAMP:20180611T162239Z\nUID:227723@bib.umontreal.ca\nDTSTART:20180611T130000Z\nDURATION:PT8H\nSUMMARY:9 h à 17 h\nLOCATION:Bibliothèque d'aménagement - Horaire de la bibliothèque\nEND:VEVENT\nBEGIN:VEVENT\nDTSTAMP:20180611T162239Z\nUID:227724@bib.umontreal.ca\nDTSTART:20180612T130000Z\nDURATION:PT8H\nSUMMARY:9 h à 17 h\nLOCATION:Bibliothèque d'aménagement - Horaire de la bibliothèque\nEND:VEVENT\nBEGIN:VEVENT\nDTSTAMP:20180611T162239Z\nUID:227725@bib.umontreal.ca\nDTSTART:20180613T130000Z\nDURATION:PT8H\nSUMMARY:9 h à 17 h\nLOCATION:Bibliothèque d'aménagement - Horaire de la bibliothèque\nEND:VEVENT\nEND:VCALENDAR\n"
        }
      },
      "LabelsMap": {
        "title": "LabelsMap",
        "type": "object",
        "additionalProperties": {
          "type": "string"
        },
        "description": "Un objet contenant une série de valeurs key/value de type:\n```\n/**\n * @type {Object.<string, string>}\n */\n ```",
        "x-examples": {
          "Example 1": {
            "property1": "string",
            "property2": "string"
          }
        }
      },
      "Periodes": {
        "$ref": "#/components/schemas/LabelsMap"
      },
      "Service": {
        "title": "Service",
        "x-stoplight": {
          "id": "vvmck7m7bb3hj"
        },
        "type": "object",
        "description": "Un objet contenant la description d'un service",
        "properties": {
          "label": {
            "type": "string"
          },
          "order": {
            "type": "integer",
            "description": "Le numéro d'ordre de tri"
          },
          "key": {
            "type": "string"
          }
        },
        "required": [
          "label",
          "order",
          "key"
        ],
        "x-examples": {
          "Example 1": {
            "label": "Prêt",
            "order": 6,
            "key": "pret"
          }
        }
      },
      "Services": {
        "x-examples": {
          "Example 1": {
            "regulier": {
              "label": "Heures d'ouverture",
              "order": 1,
              "key": "regulier"
            },
            "services": {
              "label": "Services",
              "order": 3,
              "key": "services"
            },
            "reference": {
              "label": "Référence",
              "order": 4,
              "key": "reference"
            },
            "soutien-informatique": {
              "label": "Soutien informatique",
              "order": 5,
              "key": "soutien-informatique"
            },
            "pret": {
              "label": "Prêt",
              "order": 6,
              "key": "pret"
            },
            "mediatheque": {
              "label": "Médiathèque J.-A.-DeSève",
              "order": 7,
              "key": "mediatheque"
            },
            "sdaesh": {
              "label": "Soutien SDAESH",
              "order": 8,
              "key": "sdaesh"
            }
          }
        },
        "description": "Une liste de types de services",
        "type": "object",
        "additionalProperties": {
          "$ref": "#/components/schemas/Service"
        }
      }
    },
    "responses": {
      "HorairesResponse": {
        "description": "opération réussie",
        "content": {
          "application/json": {
            "schema": {
              "oneOf": [
                {
                  "$ref": "#/components/schemas/Horaires"
                },
                {
                  "$ref": "#/components/schemas/HorairesICS"
                }
              ]
            },
            "examples": {
              "Example 1": {
                "value": [
                  {
                    "id": "1341844661",
                    "titre": "Handbook of coriander (Coriandrum sativum) : chemistry, functionality, and applications / edited by Mohamed Fawzy Ramadan",
                    "auteurs": [
                      "Mohamed Fawzy Ramadan"
                    ],
                    "url": "https://umontreal.on.worldcat.org/oclc/1341844661",
                    "categorielivraison": "en_ligne",
                    "type": "livre",
                    "editeur": "Boca Raton CRC Press",
                    "cotes": [
                      "SB351.C69"
                    ],
                    "disciplines": [
                      "amenagement"
                    ],
                    "format": "1 online resource",
                    "isbns": [
                      "9781003204626",
                      "1003204627"
                    ],
                    "image": "https://syndetics.com/index.aspx?isbn=9781003204626/SC.JPG",
                    "datenouveaute": "2023-01-09T00:00:00.000Z",
                    "datederniermiseajour": "2023-01-09T10:30:37.685Z"
                  }
                ]
              }
            }
          },
          "text/calendar": {
            "schema": {
              "$ref": "#/components/schemas/HorairesICS"
            }
          }
        }
      },
      "HorairesICSResponse": {
        "description": "Des horaires au format iCalendar",
        "content": {
          "text/calendar": {
            "schema": {
              "$ref": "#/components/schemas/HorairesICS"
            }
          }
        }
      },
      "RequestValidationError": {
        "description": "Une réponse qui documente une requête erronée",
        "content": {
          "application/json": {
            "schema": {
              "$ref": "https://raw.githubusercontent.com/bibudem/api-communs/main/src/errors.json#/components/schemas/RequestError"
            }
          }
        },
        "headers": {}
      },
      "InternalErrorResponse": {
        "description": "Description de l'erreur interne",
        "content": {
          "application/json": {
            "schema": {
              "$ref": "https://raw.githubusercontent.com/bibudem/api-communs/main/src/errors.json#/components/schemas/InternalError"
            }
          }
        }
      },
      "BibsResponse": {
        "description": "Retourne un objet JSON contenant la liste de toutes les bibliothèques ayant un horaire",
        "content": {
          "application/json": {
            "schema": {
              "$ref": "#/components/schemas/LabelsMap"
            },
            "examples": {
              "Liste des codes de bibliothèques": {
                "value": {
                  "am": "Bibliothèque d'aménagement",
                  "antenne-paramedicale": "Bibliothèque du Parc",
                  "cartotheque": "Cartothèque",
                  "ch": "Bibliothèque de chimie",
                  "conservation": "Centre de conservation Lionel-Groulx",
                  "cs": "Bibliothèque des livres rares et collections spéciales",
                  "dr": "Bibliothèque de droit",
                  "ed": "Bibliothèque Thérèse-Gouin-Décarie",
                  "gp": "Bibliothèque de géographie",
                  "ki": "Bibliothèque de kinésiologie",
                  "laval": "Campus de Laval",
                  "marcel-laurin": "Centre de conservation – 101, boul. Marcel-Laurin",
                  "mi": "Bibliothèque de mathématiques et informatique",
                  "mu": "Bibliothèque de musique",
                  "mv": "Bibliothèque de médecine vétérinaire",
                  "pa": "Bibliothèque Marguerite-d’Youville",
                  "pb": "Service du prêt entre bibliothèques",
                  "py": "Bibliothèque de physique",
                  "sa": "Bibliothèque de la santé",
                  "sciences": "Bibliothèque des sciences",
                  "ss": "Bibliothèque des lettres et sciences humaines"
                }
              }
            }
          }
        }
      },
      "ServicesResponse": {
        "description": "Example response",
        "content": {
          "application/json": {
            "schema": {
              "$ref": "#/components/schemas/Services"
            },
            "examples": {
              "Une liste de services": {
                "value": {
                  "regulier": {
                    "label": "Heures d'ouverture",
                    "order": 1,
                    "key": "regulier"
                  },
                  "services": {
                    "label": "Services",
                    "order": 3,
                    "key": "services"
                  },
                  "reference": {
                    "label": "Référence",
                    "order": 4,
                    "key": "reference"
                  },
                  "soutien-informatique": {
                    "label": "Soutien informatique",
                    "order": 5,
                    "key": "soutien-informatique"
                  },
                  "pret": {
                    "label": "Prêt",
                    "order": 6,
                    "key": "pret"
                  },
                  "mediatheque": {
                    "label": "Médiathèque J.-A.-DeSève",
                    "order": 7,
                    "key": "mediatheque"
                  },
                  "sdaesh": {
                    "label": "Soutien SDAESH",
                    "order": 8,
                    "key": "sdaesh"
                  }
                }
              }
            }
          }
        }
      },
      "PeriodesResponse": {
        "description": "opération réussie",
        "content": {
          "application/json": {
            "schema": {
              "$ref": "#/components/schemas/Periodes"
            },
            "examples": {
              "Une liste de types de périodes": {
                "value": {
                  "regulier": "Régulier",
                  "ete": "Session d'été (mai-juin)",
                  "ete1": "Horaire d'été",
                  "intra": "Horaire prolongé mi-session",
                  "fetes": "Période des fêtes",
                  "examens-finaux": "Horaire prolongé – Finaux",
                  "examens-mi-session": "Horaire prolongé – Mi-session",
                  "ferie": "Férié"
                }
              }
            }
          }
        }
      }
    },
    "parameters": {
      "fin": {
        "name": "fin",
        "in": "query",
        "required": false,
        "schema": {
          "$ref": "#/components/schemas/DateOrDurationFin"
        },
        "description": "Une date `xs:date` ou une durée `xs:duration`.\nValeur par défaut: `9999-12-31`.\nSi la valeur est une durée, alors la date de fin est calculée en additionnant cette durée à la date de début"
      },
      "bib": {
        "name": "bib",
        "in": "path",
        "schema": {
          "$ref": "https://raw.githubusercontent.com/bibudem/code-bib/master/openapi.json#/components/schemas/codeBib"
        },
        "description": "Un code de bibliothèque",
        "required": true
      },
      "debut": {
        "name": "debut",
        "in": "query",
        "required": false,
        "schema": {
          "$ref": "#/components/schemas/DateOrDurationDebut"
        },
        "description": "Une date `xs:date` ou une durée `xs:duration`. Valeur par défaut: le jour courant. Si la valeur est une durée, alors la date de début est calculée à partir de la date courante, zéro heure locale. Par exemple, `2023-02-14`"
      },
      "ouvert": {
        "name": "ouvert",
        "in": "query",
        "required": false,
        "schema": {
          "type": "boolean",
          "example": "true",
          "enum": [
            true,
            false
          ],
          "default": false
        },
        "description": "Indique si on veut uniquement les bibliothèques ouvertes pendant la période demandée."
      },
      "bibs": {
        "name": "bibs",
        "in": "query",
        "required": false,
        "schema": {
          "type": "array",
          "items": {
            "$ref": "https://raw.githubusercontent.com/bibudem/code-bib/master/openapi.json#/components/schemas/codeBib"
          }
        },
        "description": "Un ou des code(s) de bibliothèque"
      },
      "format": {
        "name": "format",
        "in": "query",
        "required": false,
        "schema": {
          "type": "string",
          "default": "json",
          "enum": [
            "json",
            "ics"
          ],
          "example": "ics"
        },
        "description": "Le format demandé: json ou ics"
      },
      "accept": {
        "name": "accept",
        "in": "header",
        "required": false,
        "schema": {
          "type": "string",
          "default": "application/json",
          "enum": [
            "application/json",
            "text/calendar"
          ],
          "example": "text/calendar"
        },
        "description": "Le format demandé: `text/calendar` ou `application/json`"
      }
    },
    "securitySchemes": {}
  },
  "servers": [
    {
      "url": "https://api.bib.umontreal.ca/horaires",
      "description": "Serveur de production"
    },
    {
      "url": "/",
      "description": "Serveur de développement"
    }
  ]
}